spring:
  application:
    name: booking-saas

  datasource:
    url: jdbc:postgresql://localhost:5432/booking_saas
    username: postgres
    password: 123321
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    url: jdbc:postgresql://localhost:5432/booking_saas
    user: postgres
    password: 123321
    locations: classpath:db/migration
    enabled: true
    validate-on-migrate: false

  jwt:
    secret_key: some-long-secret-string-at-least-64-chars-1234567890abcdef1234567890abcdef

server:
  port: ${PORT:8080}
