spring:
  application:
    name: booking-saas

  jwt:
    secret_key: AyazchikSuperKeyB0.1

  datasource:
    url: jdbc:postgresql://localhost:5432/booking_saas
    username: postgres
    password: Kanybek12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    url: jdbc:postgresql://localhost:5432/booking_saas
    user: postgres
    password: Kanybek12345
    locations: classpath:db/migration
    enabled: true
    validate-on-migrate: false

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html