spring:
  application:
    name: booking-saas

  datasource:
    url: jdbc:postgresql://dpg-d1e4kpngi27c7388qbs0-a.oregon-postgres.render.com:5432/saas_book_postgres
    username: root
    password: sVxkZhtP0MArgXESPmJnJb7udyiV13VT
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    url: jdbc:postgresql://dpg-d1e4kpngi27c7388qbs0-a.oregon-postgres.render.com:5432/saas_book_postgres
    user: root
    password: sVxkZhtP0MArgXESPmJnJb7udyiV13VT
    locations: classpath:db/migration
    enabled: true
    validate-on-migrate: false

# Email sender configuration
  mail:
    host: smtp.gmail.com
    username: zhanybek20065732@gmail.com
    password: xmqh zdnf kjld qdkh
    port: 587
    properties:
      mail:
        smtp:
          auth:
            true
          starttls:
            enable: true

  jwt:
    secret_key: some-long-secret-string-at-least-64-chars-1234567890abcdef1234567890abcdef

server:
  port: ${PORT:8080}
