spring:
  application:
    name: booking-saas

  jwt:
    secret_key: some-long-secret-string-at-least-64-chars-1234567890abcdef1234567890abcdef

  datasource:
    url: jdbc:postgresql://dpg-d1e4kpngi27c7388qbs0-a.oregon-postgres.render.com:5432/saas_book_postgres
    username: root
    password: sVxkZhtP0MArgXESPmJnJb7udyiV13VT
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    url: jdbc:postgresql://dpg-d1e4kpngi27c7388qbs0-a.oregon-postgres.render.com:5432/saas_book_postgres
    user: root
    password: sVxkZhtP0MArgXESPmJnJb7udyiV13VT
    locations: classpath:db/migration
    enabled: true
    validate-on-migrate: false

server:
  port: ${PORT:8080}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html