spring:
  application:
    name: booking-saas

  jwt:
    secret_key: some-long-secret-string-at-least-64-chars-1234567890abcdef1234567890abcdef

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    url: jdbc:postgresql://localhost:5432/booking_saas
    user: postgres
    password: Kanybek12345
    locations: classpath:db/migration
    enabled: true
    validate-on-migrate: false

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html