spring:
  application:
    name: booking-saas

  datasource:
    url: jdbc:postgresql://localhost:5432/booking_saas
    username: postgres
    password: Kanybek12345
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    url: jdbc:postgresql://localhost:5432/booking_saas
    password: Kanybek12345
    user: postgres
    locations: classpath:db/migration
    enabled: true
    validate-on-migrate: false

  # Email sender configuration
  mail:
    host: smtp.gmail.com
    username: zhanybek20065732@gmail.com
    password: xmqh zdnf kjld qdkh
    port: 587
    properties:
      mail:
        smtp:
          auth:
            true
          starttls:
            enable: true

  jwt:
    secret_key: some-long-secret-string-at-least-64-chars-1234567890abcdef1234567890abcdef

server:
  port: ${PORT:8080}
